#!/usr/bin/env python3
"""Reads file with natural numbers p and returns p=q*n to stdout.
Where q and n are factors of p

::
    Usage: factors <file>, where <file> is a file containing
    numbers to factor.

    Assumptions:
    - The file has one number per line
    - All lines will be valid natural numbers greater than 1
    - There will be no empty line, and no space before and after the
    valid number
    - The file will always end with a new line
::
"""
import sys
import math


def factorize():
    """Factorizes input natural numbers"""
    if len(sys.argv) != 2:
        sys.stdout.write("Usage: factors <file>", file=sys.stderr)
        return
    with open(sys.argv[1]) as file:
        for line in file:
            number = int(line)
            ln = 2 # Possible divisor
            sqrt_num = math.isqrt(number)
            if number % 2 == 0:
                print(f"{number}={number // 2}*2")
                continue
            for ln in range(3, sqrt_num + 1, 2):
                if number % ln == 0:
                    print(f"{number}={number // ln}*{ln}")
                    break
            else:
                print(f"{number}={number // ln}*{ln}")


if __name__ == '__main__':
    factorize()
